version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: yourUsername
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: yourDatabaseName
    ports:
      - "5434:5432"  # Corrigido para 5432, que é a porta padrão do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
