version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: yourUsername
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: yourDatabaseName
    ports:
      - "5434:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000" 
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: yourUsername
      DATABASE_PASSWORD: yourPassword
      DATABASE_NAME: yourDatabaseName
    depends_on:
      - db
    volumes:
      - .:/usr/src/app 

volumes:
  postgres_data:
